version: '3.8'

services:
  work360-hub:
    image: ghcr.io/rogartwork/work360:latest
    environment:
      - DATABASE_URL=file:/app/data/hub.db
    volumes:
      - nexus-hub-db:/app/data
      # Agora conectando no volume real da stack gs360
      - gs360_x360-data:/x360-data:ro
    networks:
      - rogartwork
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.http.routers.work360-hub.rule=Host(`portal.workmanos.com.br`)
        - traefik.http.routers.work360-hub.entrypoints=websecure
        - traefik.http.routers.work360-hub.priority=1
        - traefik.http.routers.work360-hub.tls.certresolver=letsencryptresolver
        - traefik.http.routers.work360-hub.service=work360-hub
        - traefik.http.services.work360-hub.loadbalancer.server.port=3001
        - traefik.http.services.work360-hub.loadbalancer.passHostHeader=1

volumes:
  nexus-hub-db:
    driver: local

  # Mapeamento do volume externo com o nome real do Swarm
  gs360_x360-data:
    external: true

networks:
  rogartwork:
    external: true
